name: CI with Security

on:
  push:
    branches: [ "main","master" ]
  pull_request:

# Needed so CodeQL can publish alerts
permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  build-test-and-sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python manage.py test --noinput

      - name: Run Bandit (SAST) and save report
        run: |
          pip install bandit
          bandit -r . -f txt -o bandit-report.txt || true

      - name: Install Safety
        run: pip install safety

      - name: Safety dependency scan
        run: safety check --full-report --output text > safety-report.txt || true

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "PyGoat"
          path: "."
          format: "HTML"
          out: "reports"

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.txt
            safety-report.txt
            reports

  codeql:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
